---
title: "Untitled"
format: html
---


```{r}
library(tidyverse)
```


```{r}
data <- read_delim("data/data_csv.csv", delim = ",", n_max = 10)

data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(data$`Группа крови`)

data
```

```{r}
write_delim(data, "out/data_csv.csv", delim = ",")
list.files("out")
```

```{r}
read_csv("data/data_csv.csv", skip = 0, n_max = 0)
read_csv2("data/data_csv2.csv", skip = 0, n_max = 0)
read_tsv("data/data_tsv.tsv", , skip = 0, n_max = 0)
```

```{r}
read_tsv("data/data_tsv.tsv", , skip = 0)
```

```{r}
write_csv(data, "out/data_csv.csv")
write_excel_csv(data, "out/data2_csv.csv")
```

```{r}
write_csv2(data, "out/data_csv2.csv")
write_excel_csv(data, "out/data2_csv2.csv")
```

```{r}
write_tsv(data, "out/data_tsv.tsv")
```


```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

data
```


```{r}
data

data |> select(`Группа крови`, `Рост`)

data |> select(starts_with("б"))
data |> select(contains("_E1"))
data |> select(matches("_E\\d{1}"))

data |> select(where(is.numeric))
data |> select(where(function(x) is.numeric(x) && mean(x, na.rm = TRUE) > 10))

variables <- c("Базофилы_E1", "Эозинофилы_E1", "Гемоглобин_E1")
data |> select(all_of(variables))

variables_missing <- c(variables, "Имя отсутствующей переменной")
data |> select(any_of(variables_missing))

data |> select(`Группа`, starts_with("Гемоглобин"))
data |> select(!where(is.numeric))
```


```{r}
data |> select(`Пол`, `Эритроциты_E1`, everything())

data |> relocate(contains("Эритроциты"), .after = `Группа крови`)

data |>
  select(
    `Эритроциты1` = `Эритроциты_E1`,
    `Эритроциты2` = `Эритроциты_E2`
  )

data |>
  rename(
    `Эритроциты1` = `Эритроциты_E1`,
    `Эритроциты2` = `Эритроциты_E2`
  )
```


```{r}
data |> slice(c(1, 3, 5))

data |> slice(-c(1, 3, 5))

data |> slice_head(n = 4)

data |> slice_tail(prop = 0.08)

data |> slice_sample(prop = 0.05)

data |> slice_min(`Возраст`)
```


```{r}

data |> filter(`Пол` == "Женский")

data |>
  filter(`Группа крови` %in% c("A (II)", "O (I)") & `Группа` != "Группа 1")

data |> filter(between(`Возраст`, 31, 34))

data |> filter(near(Эозинофилы_E1, 3.38, tol = 0.1))

data |> filter(if_all(.cols = contains("Базофилы"), .fns = function(x) x > 1.5))

data |> filter(if_any(.cols = contains("Базофилы"), .fns = function(x) x > 1.5))
```


```{r}
data |> arrange(`Возраст`)

data |> arrange(`Группа крови`)

data |> arrange(desc(`Рост`))

data |> arrange(desc(`Рост`), `Возраст`)
```


```{r}
data |> filter(`Возраст` > mean(`Возраст`))

data |>
  group_by(`Группа`) |>
  filter(`Возраст` > mean(`Возраст`))

data |>
  group_by(`Группа`) |>
  arrange(`Возраст`, .by_group = TRUE)

data |> group_by(`Группа`) |> ungroup()
```


```{r}
tibble(var_1 = 1:10, var_2 = var_1 + 1.123) |>
  mutate(
    var_sum = var_1 + var_2,
    var_minus = var_1 - var_2,
    var_multiple = var_1 * var_2,
    var_divide = var_1 / var_2,
    var_1_log = log(var_1),
    var_1_log1p = log1p(var_1),
    var_1_exp = exp(var_1_log),
    var_1_exm1 = expm1(var_1_log1p),
    var_2_round = round(var_2, 2),
    var_2_ceil = ceiling(var_2),
    var_2_floor = floor(var_2)
  )

data |>
  mutate(
    `Женщины с четвёртой группой крови` = if_else(
      `Пол` == "Женский" & `Группа крови` == "AB (IV)",
      "Да",
      "Нет"
    )
  ) |>
  select(`Женщины с четвёртой группой крови`, everything()) |>
  arrange(`Женщины с четвёртой группой крови`)

data |>
  mutate(
    `Возрастная группа` = case_when(
      `Возраст` < 20 ~ "< 20",
      between(`Возраст`, 20, 30) ~ "20 - 30",
      `Возраст` > 30 ~ "> 30"
    ),
    `Возрастная группа` = factor(
      `Возрастная группа`,
      levels = c("< 20", "20 - 30", "> 30")
    )
  ) |>
  select(`Возраст`, `Возрастная группа`)
```


```{r}
data |>
  mutate(across(where(is.numeric), function(x) {
    (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
  }))

data |>
  mutate(across(contains("E1"), function(x) {
    (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
  }))

data |>
  mutate(across(
    where(function(x) is.numeric(x) && mean(x, na.rm = TRUE) < 10),
    function(x) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
  ))

data |>
  group_by(`Группа`) |>
  mutate(across(contains("Базофилы"), function(x) x - mean(x, na.rm = TRUE))) |>
  ungroup() |>
  select(`Группа`, contains("Базофилы"))

data |> mutate(`Группа` = NULL)
```


```{r}
data |>
  mutate(
    `Базофилы_E1` = if_else(
      is.na(`Базофилы_E1`),
      mean(`Базофилы_E1`, na.rm = TRUE),
      `Базофилы_E1`
    )
  )

data |>
  mutate(
    `Группа крови` = as.character(`Группа крови`),
    `Группа крови` = replace_na(`Группа крови`, "Нет данных")
  )

data |>
  mutate(`Группа крови` = fct_na_value_to_level(`Группа крови`, "Нет данных"))

data |>
  mutate(`Группа крови` = na_if(`Группа крови`, "B (III)"))

data |>
  mutate(
    `Группа крови` = fct_na_level_to_value(
      `Группа крови`,
      extra_levels = "B (III)"
    )
  )
```


```{r}
data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), function(x) mean(x, na.rm = TRUE)))

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
```


```{r}
data |>
  group_by(`Группа`) |>
  summarise(n = length(na.omit(`Группа крови`)))

data |>
  select(`Группа`, where(is.factor)) |>
  mutate(
    `Группа крови` = fct_na_value_to_level(`Группа крови`, "Нет данных")
  ) |>
  count(`Группа`, `Группа крови`) |>
  group_by(`Группа`) |>
  mutate(`Процент по группе` = n / sum(n) * 100) |>
  ungroup() |>
  mutate(`Процент по выборке` = n / sum(n) * 100) |>
  mutate(across(starts_with("Процент"), function(x) str_c(round(x, 2), "%")))

data |> distinct(`Группа`, .keep_all = TRUE)
```


```{r}
tibble(var = "first part__second_part") |>
  separate(var, into = c("var_1", "var_2"), sep = "__")

tibble(var = "first part__second_part") |>
  separate(var, into = c("var_1", "var_2"), sep = "__") |>
  unite("new_var", var_1, var_2, sep = " AND ")
```


```{r}
set.seed(1)

data_1 <- tibble(var_1 = 1:10, var_2 = rep(c("Группа 1", "Группа 2"), 5))
data_2 <- tibble(var_2 = runif(10, 0, 1), var_3 = rnorm(10))
data_3 <- tibble(
  var_4 = 100:91,
  var_5 = rep(c("Молодые", "Средний возраст"), 5)
)

data_1 |>
  bind_cols(data_2) |>
  bind_cols(data_3)

data_1 <- tibble(var_1 = "var 1", var_2 = "var 2", var_3 = "var 3")
data_2 <- tibble(var_1 = "var 1", var_2 = "var 2")
data_3 <- tibble(var_1 = "var 1", var_2 = "var 2")

data_1 |>
  bind_rows(data_2) |>
  bind_rows(data_3)
```


```{r}
data_1 <- tibble(var_1 = 1:8) |>
  mutate(id = row_number())

data_2 <- tibble(var_2 = LETTERS) |>
  mutate(`Subject ID` = row_number()) |>
  slice(-1)

data_1
data_2

data_1 |>
  left_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  right_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  inner_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  full_join(data_2, by = c("id" = "Subject ID"))
```


```{r}
data |>
  select(Группа, contains("E1")) |>
  mutate(ID = row_number()) |>
  pivot_longer(!c(Группа, ID))

data |>
  select(Группа, contains("E1")) |>
  mutate(ID = row_number()) |>
  pivot_longer(!c(Группа, ID)) |>
  pivot_wider(id_cols = c(ID, Группа))
```


```{r}
data |>
  rename_with(function(x) str_replace_all(x, c("_E1" = "1", "_E2" = "2")))

data |>
  rename_with(.cols = where(is.numeric), .fn = function(x) {
    str_c(x, " КОЛИЧЕСТВЕННАЯ ПЕРЕМЕННАЯ")
  })
```


```{r}
library(tidyverse)
library(flextable)

data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)

table |>
  flextable()
```


```{r}
table |>
  flextable() |>
  theme_alafoli()
#theme_box()
#theme_apa()
```

```{r}
table |>
  flextable() |>
  theme_box() |>
  merge_v(c("Группа", "Переменная"))

tibble(var_1 = c("p-value", "0.001"), var_2 = c("p-value", "0.05")) |>
  flextable() |>
  theme_box() |>
  merge_h(i = 1)
```


```{r}
table <- tibble(
  `Adverse events` = c(
    "SOC Желудочно-кишечные нарушения 10017947",
    "PT Тошнота 10028813",
    "SOC Нарушения со стороны нервной системы 10029205",
    "PT Головная боль 10019211"
  )
)

table |>
  flextable() |>
  theme_box() |>
  align(align = "center", part = "all")

table |>
  flextable() |>
  theme_box() |>
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |>
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |>
  bold(i = ~ str_detect(`Adverse events`, "SOC")) |>
  italic(i = ~ str_detect(`Adverse events`, "PT")) |>
  width(width = 2)
```


```{r}
is_pvalue_sign <- function(x) {
  as.numeric(str_remove(x, "<")) <= 0.05
}

table <- tibble("p-value" = c("<0.001", "0.38", "0.124", "0.005", "0.05"))

table |>
  flextable() |>
  theme_box() |>
  color(i = ~ is_pvalue_sign(`p-value`), color = "orange")

table |>
  flextable() |>
  theme_box() |>
  bg(i = ~ is_pvalue_sign(`p-value`), bg = "orange")
```